### PR TITLE
Create CONTRIBUTING.md

### LINKED ISSUE #74: Add Contributing.md file
I want to add a Contributing.md file to the repository to help the contributors, especially the beginners for a better and easy contribution.

### PR DESCRIPTION
**Pull request by Priyanshu2631**
Added the contributing.md file to this repository, fixes #74

### CODE REVIEW

**Review by Kritika30032002 — APPROVED** [review]

**Review by Kritika30032002 — CHANGES_REQUESTED** [review]
Add commands for required steps

**Comment by Priyanshu2631** [comment]
> Add commands for required steps

The commands are in the readme.md only, can u be a bit specific which commands u want

**Comment by Kritika30032002** [comment]
@Niharika0104  Review it once

**Comment by Niharika0104** [comment]
@Priyanshu2631 That's not how you write contributing.md.Where are the commands that are used set our project locally?

**Comment by Priyanshu2631** [comment]
> @Priyanshu2631 That's not how you write contributing.md.Where are the commands that are used set our project locally?

Okk mam got you, will put them in the file

**Pull request closed without merging**
