### PR TITLE
Add Custom Scrollbar

### PR DESCRIPTION
**Pull request by mryashsinghal**
- Implemented a custom scrollbar across the entire website using custom CSS and TailwindCSS.
- Applied a color scheme that matches the website's design, primarily using theme colors.
- Added smooth transitions and hover effects to enhance interactivity and user experience.
- Ensured compatibility with both WebKit-based browsers and Firefox.

### CODE REVIEW

**Comment by Kritika30032002** [comment]
attach video showing changes

**Comment by mryashsinghal** [comment]
https://github.com/Niharika0104/TrendTrove/assets/152426138/f5beb299-b4a1-467e-9b3f-5f96cb05213b

**Comment by Niharika0104** [comment]
@mryashsinghal Cool will merge it

**Comment by mryashsinghal** [comment]
I have made the Pull Request but it has not been merged yet.

**Review by Niharika0104 — APPROVED** [review]
looks good to merge

**Pull request merged**
