### PR TITLE
Updated UI of Home page

### PR DESCRIPTION
**Pull request by mdkaifansari04**
**Title**: [Enhancement] Landing Page UI Update

**Description**
Currently, all the cards and sections are not aligned with their parent elements, resulting in a poor user experience. The design needs to be updated to enhance visual appeal and usability. The following elements need design improvements:

- Navbar
- Searchbar
- Carousel
- Featured section
- Category section
- Product Card

**Related Issue**
This PR addresses issue #48.

**Changes Made**
- Aligned all cards and sections properly with their parent elements.
- Updated the design of the Navbar for better navigation.
- Enhanced the Searchbar for improved usability.
- Refreshed the Carousel design to make it more engaging.
- Redesigned the Featured section for better highlighting of key products.
- Improved the layout of the Category section for easier browsing.
- Updated the Product Card design for better visual appeal.

**To Reproduce**
1. Navigate to the home route or visit - [Trend Trove](https://trend-trove-client-side.vercel.app/)

**Screenshots**
image
image
image
image

**Testing Instructions**
1. Pull this branch.
2. Navigate to the home route.
3. Verify that all elements are aligned properly and the UI changes are visible.

**Checklist**
- [x] Alignment issues fixed.
- [x] Navbar design updated.
- [x] Searchbar enhanced.
- [x] Carousel redesigned.
- [x] Featured section improved.
- [x] Category section layout updated.
- [x] Product Card design refreshed.

**Reviewer Notes**
There was some responsiveness error with tailwindcss. It can be handled in another issue

### CODE REVIEW

**Comment by Niharika0104** [comment]
@mdkaifansari04 you created pull request on the main branch.Create a new branch and move your code to that branch and then raise a pr.And also resolve the merge conflicts.

**Comment by mdkaifansari04** [comment]
Yeah I actually have put the changes in the main branch. I'll surely update that by tomorrow.

**Comment by Kritika30032002** [comment]
@mdkaifansari04

**Comment by Kritika30032002** [comment]
@mdkaifansari04 Any updates?

**Pull request closed without merging**
