### PR TITLE
improved the search functionality of the search component 

### PR DESCRIPTION
**Pull request by Rajneesh2223**
PR #33  
  I have modified the search functionality  by changing it to onclick event

### CODE REVIEW

**Comment by Rajneesh2223** [comment]
Uploading TrendTrove - Google Chrome 2024-06-14 11-10-57.mp4…

_**this is the demo video of search functionality.**__

**Comment by Rajneesh2223** [comment]
https://github.com/Niharika0104/TrendTrove/assets/127289297/87a3be17-a969-4c8c-a0e3-19c9a82d548c
here is the demo of search functionality

**Comment by Niharika0104** [comment]
@Rajneesh2223 hey..instead of performing search functionality on the cards which are there are on the home page,just redirect them to that page.Like when user types sarees and clicks on search take them /sarees page this is already set on the category cards(like when u click on saree card you will be redirected to sarees pages).You also do the same,becoz in e commerce applications like Myntra and Amazon whenever you search for something you will be redirected to a page with the products that you searched for.And remove that clear button on navbar,it's not needed.

**Comment by Rajneesh2223** [comment]
thanks for the review i will work on it .

**Comment by Rajneesh2223** [comment]
https://github.com/Niharika0104/TrendTrove/assets/127289297/2f188646-eb4e-41c2-a14c-0de02042a3bb

@Niharika0104  
I have changed the implementation of search bar , please review so that i can make pull request . If any changes required I will do it

**Comment by Niharika0104** [comment]
image
@Rajneesh2223  I merged the code your video shows something what's been deployed it shows something else.Also,when users types on sarees and clicks on search redirect them sarees page(https://trend-trove-client-side.vercel.app/Sarees) right now you are 
only filtering on the home page category cards.Did you push the changes to the pr?

**Comment by Rajneesh2223** [comment]
Ma'am i just send you the video  I havent made the pull request , that why It is showing this

**Pull request merged**
