### PR TITLE
feat: Added Not Found Page #29

### LINKED ISSUE #29: 404 Not Found Page Should Be Present In Our Webite
**Is your feature request related to a problem? Please describe.**
Yes, Sometimes User explicitly enter some routes like /Dashboard ,etc . where we does not have to show them some ui.
in our case , our web app showing navbar to the user and loader which lead to user think that some page is to be come .

**Describe the solution you'd like**
404 Not Found Page Should Be Present  Which Tell the User , This Request route is not present

**Describe alternatives you've considered**
Alternative can be like if user come explicitly to the route that doesn't exist we have to route them home page

**Additional context**
Screenshot 2024-06-07 195640

### PR DESCRIPTION
**Pull request by Chetax**
# Fixes  #29 
# 👨‍💻 Changes proposed(What did you do ?)

 -Added Not Found Page To Avoid User Undefinite Navigation to the our website
 - In The Assests Folder Added Image Folder And Keepted one not found image
 
# 🎞️Screenshot 
 
Screenshot 2024-06-07 204012

# ✔️ Check List (Check all the applicable boxes)
- [X] My code follows the code style of this project With No Conflict.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.

### CODE REVIEW

**Review by captainsahil001 — CHANGES_REQUESTED** [review]
is the picture reusable means non copyrighted right?

**Comment by Chetax** [comment]
> is the picture reusable means non copyrighted right?

Not Sure But let me change the image and add attribute to the  image

**Comment by Chetax** [comment]
@captainsahil001 sir I done With Adding Attributing to image

**Review by captainsahil001 — APPROVED** [review]
nice

**Comment by Niharika0104** [comment]
@Chetax you created pr on the main branch.Move you code to new branch and then raise the pr.

**Comment by Niharika0104** [comment]
@Chetax  you created pr on main branch.Move your code to a new branch and raise a pr from that branch

**Pull request closed without merging**
