### PR TITLE
fix: 69, Included bestsellers and ui edit

### PR DESCRIPTION
**Pull request by RohittCodes**
### Made a few changes:
- included a separate route to fetch `bestsellers`. sorting is done based on the sales of the product, to make it fair i've used sales percentage as the metric.
- fixed the ui of product component where the text wasn't visible earlier.

image

### CODE REVIEW

**Comment by Niharika0104** [comment]
@RohittCodes Can you please change the ui according to the one that is there in the other categories?

**Comment by RohittCodes** [comment]
okay, i'll change the background but didn't understood what u meant by,
> change the ui according to the one that is there in the other categories

Not sure if i'm correct, but the issue was to create a section for best selling products, and to change the ui same as categories, it would need to create a separate component.

**ps**: the product desc isn't visible in the product card
image

**Comment by Niharika0104** [comment]
@RohittCodes I mean just look at the cards that are there in the other categories.Make sure that your cards which are there in the best selling category has same design as the other category cards.We want the ui to be uniform across the site.

**Comment by Kritika30032002** [comment]
> @RohittCodes I mean just look at the cards that are there in the other categories.Make sure that your cards which are there in the best selling category has same design as the other category cards.We want the ui to be uniform across the site.

make a separate component for product card

**Comment by Niharika0104** [comment]
@Kritika30032002 @RohittCodes  Nah just use the same card that exists in the other categories

**Comment by RohittCodes** [comment]
okay sure.

**Pull request closed without merging**
