### PR TITLE
added the api endpoints in controllers folder 

### PR DESCRIPTION
**Pull request by Rajneesh2223**
PR #52  
@Niharika0104 
I have made the changes as requested and refactored the user endpoint to use the MVC architecture. Please review the updated implementation. I have also added a video demonstrating the implemented functionality.

https://github.com/Niharika0104/TrendTrove/assets/127289297/832f28b2-9722-4b71-8067-ecbb4682c725

### CODE REVIEW

**Comment by Niharika0104** [comment]
Cool!But there are merge conflicts,please resolve them so that I can merge the code.

**Comment by Rajneesh2223** [comment]
Yeah I have resolved that

**Comment by Rajneesh2223** [comment]
..

**Comment by Kritika30032002** [comment]
@Niharika0104

**Pull request closed without merging**
