### PR TITLE
added the authentication endpoint api

### PR DESCRIPTION
**Pull request by Rajneesh2223**
fiexd  PR  #99 
 I have implement the logic of  user authentication and created the user endpoint for each part .

Refactor: Restructure /profile endpoint for JWT authentication

- Removed premature response and reorganized token verification and user data retrieval.
- Added error handling for failed JWT verification.
- Ensured single response for fetching user profile data.

### CODE REVIEW

**Comment by Kritika30032002** [comment]
@Rajneesh2223  show video of implemented functionality

**Comment by Rajneesh2223** [comment]
https://github.com/Niharika0104/TrendTrove/assets/127289297/7306f1e9-1f26-4479-be41-65e9a8520a1c

here is the video

**Comment by Niharika0104** [comment]
Hey I used MVC architecture add those end points in authController file under controller folder and see how other end points are set.Currently,you added them directly in the index.js

**Comment by Rajneesh2223** [comment]
I will change it now . and else if fine ?

**Comment by Kritika30032002** [comment]
@Rajneesh2223 Are the changes done?

**Comment by Rajneesh2223** [comment]
yeah i have made a pr of this.

**Pull request closed without merging**
