### PR TITLE
Updated sorting and filtering feature in Products section issue Adding of a refine(filter) functionality current ,based on the price , discount , brand name in respective products section. #80

### PR DESCRIPTION
**Pull request by jeevan10017**
done issue #80 
#80 

https://github.com/Niharika0104/TrendTrove/assets/132948936/1a161506-b46c-4d0f-ba1c-205f9e3a20ce

Screenshot 2024-06-20 193600

filtering by the price, I am getting an issue

### CODE REVIEW

**Comment by Niharika0104** [comment]
looks amazing! @jeevan10017  but there are merge conflicts please resolve them.

**Comment by jeevan10017** [comment]
@Niharika0104  Conflicts resolved

**Comment by Kritika30032002** [comment]
@Niharika0104

**Comment by Niharika0104** [comment]
@jeevan10017 What issue are you facing while filtering price @chirantanbanik Can you help him regarding this.

**Comment by jeevan10017** [comment]
@Niharika0104 @chirantanbanik , 
Issue with sorting price from low to high and high to low 
-> It is sorting independently for 3-digit prices and 4-digit prices.
For example => If I select the sort option (low to high) 
                       products sorting first with ₹1000  -> ₹3300 (Highest price of product)  then ₹ 329(lowest price of product) -> ₹ 999

Logic used for it 
` updatedData.sort((a, b) => {
      const priceA = parsePrice(a.discountprice);
      const priceB = parsePrice(b.discountprice);

      switch (selectedSort) {
        case 'price-asc':
          return priceA - priceB;
        case 'price-desc':
          return priceB - priceA;
}`

**Pull request merged**
